### ISSUE TITLE
Expectations

### ISSUE THREAD

**Issue by albfan** [apmasell/treesitter4j#1]
So what features would this provide?

AST in java is great, but: does this need to reimplement existing tree sitter parsers?

Is there any minimal example?

**Comment by apmasell** [comment]
Well, it doesn't work yet, so no, there are no examples.

I'm in the process of porting the “runtime” portion of TreeSitter that works off of a state transition table. I intend to reimplement the compiler portion (what turns a grammar into the state transition table). The interface for this would look similar to the JavaScript library.

In the TreeSitter grammar, each node is identified by a string. In this port, I would like that to be a generic type so that I can fill the tree with Java enums or other types that can actually process the tree.

I don't have much use for existing grammars for my project, but it should be straight forward to read the JSON from of the grammar and build the grammar using the Java interface or vice-versa.

It might also be worthwhile to build a tool that can emit the state transition table as JVM bytecode for easy consumption. That would require some way to reconstitute the symbol names–easy for Strings and enums, difficult for other types.

The existing TreeSitter code uses a sort of lexer that's implemented as C code, so each lexer would have to be ported to Java.

What functionality are you looking for?

**Comment by albfan** [comment]
I want to parse any source code and build AST trees for them. I guess grammars are needed for that, what other usages have tree-sitter?

I'm just good at java so see a java implementation of tree-sitter can help me to understand it in deep

**Comment by apmasell** [comment]
I'm planning to use it for a compiler for [Flabbergast](https://github.com/flabbergast-config/flabbergast).

Would you be interested in helping implementation?

**Comment by albfan** [comment]
Maybe if you need to support parsers. If you can define what is missing to parse a grammar (say a json test file) and build an AST for it. If you need that and you open an issue, just mention me on it

I checked https://fiddle.flabbergast.org/Default.aspx?saved=2597068289 (sql example) but I think is not on my radar
